### ISSUE TITLE
里面的方法有没有使用说明呢？

### ISSUE THREAD

**Issue by LeonBiters** [shaoyuan1943/AMRVoiceRecorder#2]

**Comment by LeonBiters** [comment]
- (int)WAV2AMR:(nonnull NSString *)wavFile amr:(nonnull NSString *)amrFile
  这个方法怎么用呢？

**Comment by shaoyuan1943** [comment]
这个是静态方法，直接[实例 方法]调用就可以了，参数一个是wav文件路径，一个是amr文件路径

**Comment by NorahWu** [comment]
录制出来的.wav格式文件不能转化为.amr的音频啊,而且苹果不能录制.amr的音频。怎么解决呢 @shaoyuan1943 @LeonBiters

**Comment by shaoyuan1943** [comment]
是可以转换的，我的代码里有注释噢~苹果在ios 4.3之后就不能直接录制amr音频了，所以后面只能通过软解加转换的方式实现amr音频。具体的你可以看：http://shaoyuan1943.github.io/2016/02/26/chat-in-game-three/

**Comment by NorahWu** [comment]
转好了  忘了过来回复了 谢谢
